server:
  port: 4500
  ssl:
    enabled: true
    key-store: file:d:/Java SpringBoot Web App/keystore.p12
    key-store-password: password
    key-store-type: PKCS12
    key-alias: identityhub

spring:
  application:
    name: Java SpringBoot Web App
  security:
    oauth2:
      client:
        registration:
          identityhub:
            client-id: ee772e0e-4f95-48a5-8bbb-f2adb0696109
            client-secret: fU3OTIb4zT0bzyItYvq6gELBF909uiKASDJBHL1M6c8=
            client-authentication-method: none
            scope: openid,profile,email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/signin-oidc"
            client-name: IdentityHub
        provider:
          identityhub:
            issuer-uri: https://id.demo.operlity.com
            user-name-attribute: preferred_username

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG

thymeleaf:
  cache: false
